// <auto-generated />
using System;
using CFU.UniversityManagement.Infrastructure;
using CFU.UniversityManagement.Infrastructure.Structure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CFU.UniversityManagement.WebAPI.Migrations
{
    [DbContext(typeof(UniversityManagementDBContext))]
    [Migration("20220312173055_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CFU.Domain.StructureContext.AcademyAggregate.Academy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDisbanded")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("academies", (string)null);
                });

            modelBuilder.Entity("CFU.Domain.StructureContext.AcademyAggregate.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcademyId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId1");

                    b.ToTable("faculties", (string)null);
                });

            modelBuilder.Entity("CFU.Domain.StructureContext.AcademyAggregate.Faculty", b =>
                {
                    b.HasOne("CFU.Domain.StructureContext.AcademyAggregate.Academy", null)
                        .WithMany("Faculties")
                        .HasForeignKey("AcademyId1");
                });

            modelBuilder.Entity("CFU.Domain.StructureContext.AcademyAggregate.Academy", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
